# Production image for the Medusa v2 backend (backend/), built from the
# repo root so pnpm can resolve the workspace (backend + storefront share a
# lockfile). Build context MUST be the repo root:
#
#   docker build -f Dockerfile -t dont-tell-mama-backend .
#
# or, for Cloud Run's source deploy, run `gcloud run deploy` from the repo
# root (see backend/CLOUD_RUN_DEPLOY.md) so it picks this file up.

ARG NODE_VERSION=20-slim

# ---------------------------------------------------------------------------
# deps: install only the backend workspace's dependencies (incl. devDeps —
# `medusa build` needs the TypeScript toolchain), using the shared lockfile.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS deps
WORKDIR /app
RUN corepack enable

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY backend/package.json ./backend/package.json
# pnpm needs every workspace member's package.json to resolve the graph, but
# --filter below means only backend's deps actually get installed/downloaded.
COPY storefront/package.json ./storefront/package.json

RUN pnpm install --filter backend... --frozen-lockfile

# ---------------------------------------------------------------------------
# build: compile the backend and produce the .medusa/server production
# output (this is Medusa's own documented build artifact, see
# https://docs.medusajs.com/learn/deployment/general).
# ---------------------------------------------------------------------------
FROM deps AS build
WORKDIR /app
COPY backend ./backend
WORKDIR /app/backend
RUN pnpm build

# .medusa/server ships its own package.json (generated by `medusa build`,
# deliberately separate from backend/package.json) — install its production
# dependencies there per Medusa's documented deploy flow.
WORKDIR /app/backend/.medusa/server
RUN npm install --omit=dev

# ---------------------------------------------------------------------------
# runtime: slim final image — only the built server + its prod node_modules,
# nothing from the build toolchain (no TypeScript, no source, no pnpm cache).
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS runtime
ENV NODE_ENV=production
WORKDIR /app

COPY --from=build /app/backend/.medusa/server ./

# Cloud Run injects PORT at runtime (defaults to 8080) and Medusa's CLI
# already respects process.env.PORT (falls back to 9000 only if unset) —
# same mechanism already verified working on Render, no code change needed.
EXPOSE 8080

# Runs pending DB migrations, then starts the server. Safe to run on every
# cold start: migrations are idempotent (no-op if nothing pending).
CMD ["sh", "-c", "npm run predeploy && npm run start"]
